exclude: ^main_app/migrations/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: ^offer_me/settings.py
        args:
            - '--max-line-length=121'
            - '--max-complexity=10'
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.33.0
    hooks:
      - id: djlint-reformat-django
-   repo: 'https://github.com/psf/black'
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.11
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
