ARG PYTHON_VERSION=3.12.2
FROM python:${PYTHON_VERSION}-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_VIRTUALENVS_CREATE=false
WORKDIR /tests
COPY poetry.lock pyproject.toml /tests/
RUN pip install -U pip && pip install pytest-playwright==0.4.4
RUN playwright install-deps && playwright install
COPY /automated_tests /tests/
