ARG PYTHON_VERSION=3.12.2
FROM python:${PYTHON_VERSION}-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PLATFORM=linux/arm
WORKDIR /tests
COPY test_requirements.txt /tests/
RUN pip install -U pip
RUN pip install -r test_requirements.txt
RUN playwright install-deps && playwright install
COPY /automated_tests /tests/
