# Generated by Django 4.2.6 on 2023-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('is_remote', models.BooleanField()),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
