# Generated by Django 5.0 on 2023-12-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('is_remote', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], default='Remote', max_length=6)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('url', models.URLField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
